// Code generated by go-swagger; DO NOT EDIT.

package volume_storage_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRuntimeVolumeHandlerFunc turns a function with the right signature into a get runtime volume handler
type GetRuntimeVolumeHandlerFunc func(GetRuntimeVolumeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRuntimeVolumeHandlerFunc) Handle(params GetRuntimeVolumeParams) middleware.Responder {
	return fn(params)
}

// GetRuntimeVolumeHandler interface for that can handle valid get runtime volume params
type GetRuntimeVolumeHandler interface {
	Handle(GetRuntimeVolumeParams) middleware.Responder
}

// NewGetRuntimeVolume creates a new http.Handler for the get runtime volume operation
func NewGetRuntimeVolume(ctx *middleware.Context, handler GetRuntimeVolumeHandler) *GetRuntimeVolume {
	return &GetRuntimeVolume{Context: ctx, Handler: handler}
}

/*GetRuntimeVolume swagger:route GET /runtimeEnvironments/{providerIdRE}/applications/{providerIdAI}/volumes Volume storage management getRuntimeVolume

Get RuntimeVolume

*/
type GetRuntimeVolume struct {
	Context *middleware.Context
	Handler GetRuntimeVolumeHandler
}

func (o *GetRuntimeVolume) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRuntimeVolumeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
