// Code generated by go-swagger; DO NOT EDIT.

package environment_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddRuntimeEnvironmentHandlerFunc turns a function with the right signature into a add runtime environment handler
type AddRuntimeEnvironmentHandlerFunc func(AddRuntimeEnvironmentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddRuntimeEnvironmentHandlerFunc) Handle(params AddRuntimeEnvironmentParams) middleware.Responder {
	return fn(params)
}

// AddRuntimeEnvironmentHandler interface for that can handle valid add runtime environment params
type AddRuntimeEnvironmentHandler interface {
	Handle(AddRuntimeEnvironmentParams) middleware.Responder
}

// NewAddRuntimeEnvironment creates a new http.Handler for the add runtime environment operation
func NewAddRuntimeEnvironment(ctx *middleware.Context, handler AddRuntimeEnvironmentHandler) *AddRuntimeEnvironment {
	return &AddRuntimeEnvironment{Context: ctx, Handler: handler}
}

/*AddRuntimeEnvironment swagger:route POST /runtimeEnvironments Environment management addRuntimeEnvironment

Create RuntimeEnvironment

*/
type AddRuntimeEnvironment struct {
	Context *middleware.Context
	Handler AddRuntimeEnvironmentHandler
}

func (o *AddRuntimeEnvironment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddRuntimeEnvironmentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
