// Code generated by go-swagger; DO NOT EDIT.

package environment_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteRuntimeEnvironmentHandlerFunc turns a function with the right signature into a delete runtime environment handler
type DeleteRuntimeEnvironmentHandlerFunc func(DeleteRuntimeEnvironmentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteRuntimeEnvironmentHandlerFunc) Handle(params DeleteRuntimeEnvironmentParams) middleware.Responder {
	return fn(params)
}

// DeleteRuntimeEnvironmentHandler interface for that can handle valid delete runtime environment params
type DeleteRuntimeEnvironmentHandler interface {
	Handle(DeleteRuntimeEnvironmentParams) middleware.Responder
}

// NewDeleteRuntimeEnvironment creates a new http.Handler for the delete runtime environment operation
func NewDeleteRuntimeEnvironment(ctx *middleware.Context, handler DeleteRuntimeEnvironmentHandler) *DeleteRuntimeEnvironment {
	return &DeleteRuntimeEnvironment{Context: ctx, Handler: handler}
}

/*DeleteRuntimeEnvironment swagger:route DELETE /runtimeEnvironments/{providerId} Environment management deleteRuntimeEnvironment

Delete RuntimeEnvironment

*/
type DeleteRuntimeEnvironment struct {
	Context *middleware.Context
	Handler DeleteRuntimeEnvironmentHandler
}

func (o *DeleteRuntimeEnvironment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteRuntimeEnvironmentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
