// Code generated by go-swagger; DO NOT EDIT.

package environment_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteRuntimeEnvironmentOKCode is the HTTP code returned for type DeleteRuntimeEnvironmentOK
const DeleteRuntimeEnvironmentOKCode int = 200

/*DeleteRuntimeEnvironmentOK RuntimeEnvironment deleted

swagger:response deleteRuntimeEnvironmentOK
*/
type DeleteRuntimeEnvironmentOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteRuntimeEnvironmentOK creates DeleteRuntimeEnvironmentOK with default headers values
func NewDeleteRuntimeEnvironmentOK() *DeleteRuntimeEnvironmentOK {

	return &DeleteRuntimeEnvironmentOK{}
}

// WithPayload adds the payload to the delete runtime environment o k response
func (o *DeleteRuntimeEnvironmentOK) WithPayload(payload string) *DeleteRuntimeEnvironmentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete runtime environment o k response
func (o *DeleteRuntimeEnvironmentOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRuntimeEnvironmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteRuntimeEnvironmentBadRequestCode is the HTTP code returned for type DeleteRuntimeEnvironmentBadRequest
const DeleteRuntimeEnvironmentBadRequestCode int = 400

/*DeleteRuntimeEnvironmentBadRequest Bad request

swagger:response deleteRuntimeEnvironmentBadRequest
*/
type DeleteRuntimeEnvironmentBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteRuntimeEnvironmentBadRequest creates DeleteRuntimeEnvironmentBadRequest with default headers values
func NewDeleteRuntimeEnvironmentBadRequest() *DeleteRuntimeEnvironmentBadRequest {

	return &DeleteRuntimeEnvironmentBadRequest{}
}

// WithPayload adds the payload to the delete runtime environment bad request response
func (o *DeleteRuntimeEnvironmentBadRequest) WithPayload(payload string) *DeleteRuntimeEnvironmentBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete runtime environment bad request response
func (o *DeleteRuntimeEnvironmentBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRuntimeEnvironmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteRuntimeEnvironmentNotFoundCode is the HTTP code returned for type DeleteRuntimeEnvironmentNotFound
const DeleteRuntimeEnvironmentNotFoundCode int = 404

/*DeleteRuntimeEnvironmentNotFound Not found

swagger:response deleteRuntimeEnvironmentNotFound
*/
type DeleteRuntimeEnvironmentNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteRuntimeEnvironmentNotFound creates DeleteRuntimeEnvironmentNotFound with default headers values
func NewDeleteRuntimeEnvironmentNotFound() *DeleteRuntimeEnvironmentNotFound {

	return &DeleteRuntimeEnvironmentNotFound{}
}

// WithPayload adds the payload to the delete runtime environment not found response
func (o *DeleteRuntimeEnvironmentNotFound) WithPayload(payload string) *DeleteRuntimeEnvironmentNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete runtime environment not found response
func (o *DeleteRuntimeEnvironmentNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRuntimeEnvironmentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteRuntimeEnvironmentInternalServerErrorCode is the HTTP code returned for type DeleteRuntimeEnvironmentInternalServerError
const DeleteRuntimeEnvironmentInternalServerErrorCode int = 500

/*DeleteRuntimeEnvironmentInternalServerError Internal error

swagger:response deleteRuntimeEnvironmentInternalServerError
*/
type DeleteRuntimeEnvironmentInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteRuntimeEnvironmentInternalServerError creates DeleteRuntimeEnvironmentInternalServerError with default headers values
func NewDeleteRuntimeEnvironmentInternalServerError() *DeleteRuntimeEnvironmentInternalServerError {

	return &DeleteRuntimeEnvironmentInternalServerError{}
}

// WithPayload adds the payload to the delete runtime environment internal server error response
func (o *DeleteRuntimeEnvironmentInternalServerError) WithPayload(payload string) *DeleteRuntimeEnvironmentInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete runtime environment internal server error response
func (o *DeleteRuntimeEnvironmentInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRuntimeEnvironmentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
