// Code generated by go-swagger; DO NOT EDIT.

package job_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRuntimeJobsHandlerFunc turns a function with the right signature into a get runtime jobs handler
type GetRuntimeJobsHandlerFunc func(GetRuntimeJobsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRuntimeJobsHandlerFunc) Handle(params GetRuntimeJobsParams) middleware.Responder {
	return fn(params)
}

// GetRuntimeJobsHandler interface for that can handle valid get runtime jobs params
type GetRuntimeJobsHandler interface {
	Handle(GetRuntimeJobsParams) middleware.Responder
}

// NewGetRuntimeJobs creates a new http.Handler for the get runtime jobs operation
func NewGetRuntimeJobs(ctx *middleware.Context, handler GetRuntimeJobsHandler) *GetRuntimeJobs {
	return &GetRuntimeJobs{Context: ctx, Handler: handler}
}

/*GetRuntimeJobs swagger:route GET /runtimeEnvironments/{providerIdRE}/applications/{providerIdAI}/jobs Job management getRuntimeJobs

Get RuntimeJobs

*/
type GetRuntimeJobs struct {
	Context *middleware.Context
	Handler GetRuntimeJobsHandler
}

func (o *GetRuntimeJobs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRuntimeJobsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
