// Code generated by go-swagger; DO NOT EDIT.

package job_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gitlab.com/kathra/kathra/kathra-services/kathra-runtimemanager/kathra-runtimemanager-go/kathra-runtimemanager-k8s/models"
)

// GetRuntimeJobsOKCode is the HTTP code returned for type GetRuntimeJobsOK
const GetRuntimeJobsOKCode int = 200

/*GetRuntimeJobsOK RuntimeJob from RuntimeAppInstance

swagger:response getRuntimeJobsOK
*/
type GetRuntimeJobsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.RuntimeJob `json:"body,omitempty"`
}

// NewGetRuntimeJobsOK creates GetRuntimeJobsOK with default headers values
func NewGetRuntimeJobsOK() *GetRuntimeJobsOK {

	return &GetRuntimeJobsOK{}
}

// WithPayload adds the payload to the get runtime jobs o k response
func (o *GetRuntimeJobsOK) WithPayload(payload []*models.RuntimeJob) *GetRuntimeJobsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get runtime jobs o k response
func (o *GetRuntimeJobsOK) SetPayload(payload []*models.RuntimeJob) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRuntimeJobsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.RuntimeJob, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRuntimeJobsBadRequestCode is the HTTP code returned for type GetRuntimeJobsBadRequest
const GetRuntimeJobsBadRequestCode int = 400

/*GetRuntimeJobsBadRequest Bad request

swagger:response getRuntimeJobsBadRequest
*/
type GetRuntimeJobsBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetRuntimeJobsBadRequest creates GetRuntimeJobsBadRequest with default headers values
func NewGetRuntimeJobsBadRequest() *GetRuntimeJobsBadRequest {

	return &GetRuntimeJobsBadRequest{}
}

// WithPayload adds the payload to the get runtime jobs bad request response
func (o *GetRuntimeJobsBadRequest) WithPayload(payload string) *GetRuntimeJobsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get runtime jobs bad request response
func (o *GetRuntimeJobsBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRuntimeJobsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRuntimeJobsNotFoundCode is the HTTP code returned for type GetRuntimeJobsNotFound
const GetRuntimeJobsNotFoundCode int = 404

/*GetRuntimeJobsNotFound Not found

swagger:response getRuntimeJobsNotFound
*/
type GetRuntimeJobsNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetRuntimeJobsNotFound creates GetRuntimeJobsNotFound with default headers values
func NewGetRuntimeJobsNotFound() *GetRuntimeJobsNotFound {

	return &GetRuntimeJobsNotFound{}
}

// WithPayload adds the payload to the get runtime jobs not found response
func (o *GetRuntimeJobsNotFound) WithPayload(payload string) *GetRuntimeJobsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get runtime jobs not found response
func (o *GetRuntimeJobsNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRuntimeJobsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRuntimeJobsInternalServerErrorCode is the HTTP code returned for type GetRuntimeJobsInternalServerError
const GetRuntimeJobsInternalServerErrorCode int = 500

/*GetRuntimeJobsInternalServerError Internal error

swagger:response getRuntimeJobsInternalServerError
*/
type GetRuntimeJobsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetRuntimeJobsInternalServerError creates GetRuntimeJobsInternalServerError with default headers values
func NewGetRuntimeJobsInternalServerError() *GetRuntimeJobsInternalServerError {

	return &GetRuntimeJobsInternalServerError{}
}

// WithPayload adds the payload to the get runtime jobs internal server error response
func (o *GetRuntimeJobsInternalServerError) WithPayload(payload string) *GetRuntimeJobsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get runtime jobs internal server error response
func (o *GetRuntimeJobsInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRuntimeJobsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
