// Code generated by go-swagger; DO NOT EDIT.

package backup_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteBackupRuntimeEnvironmentsHandlerFunc turns a function with the right signature into a delete backup runtime environments handler
type DeleteBackupRuntimeEnvironmentsHandlerFunc func(DeleteBackupRuntimeEnvironmentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteBackupRuntimeEnvironmentsHandlerFunc) Handle(params DeleteBackupRuntimeEnvironmentsParams) middleware.Responder {
	return fn(params)
}

// DeleteBackupRuntimeEnvironmentsHandler interface for that can handle valid delete backup runtime environments params
type DeleteBackupRuntimeEnvironmentsHandler interface {
	Handle(DeleteBackupRuntimeEnvironmentsParams) middleware.Responder
}

// NewDeleteBackupRuntimeEnvironments creates a new http.Handler for the delete backup runtime environments operation
func NewDeleteBackupRuntimeEnvironments(ctx *middleware.Context, handler DeleteBackupRuntimeEnvironmentsHandler) *DeleteBackupRuntimeEnvironments {
	return &DeleteBackupRuntimeEnvironments{Context: ctx, Handler: handler}
}

/*DeleteBackupRuntimeEnvironments swagger:route DELETE /runtimeEnvironments/{providerId}/backups/{providerIdBackup} Backup management deleteBackupRuntimeEnvironments

Delete backup

*/
type DeleteBackupRuntimeEnvironments struct {
	Context *middleware.Context
	Handler DeleteBackupRuntimeEnvironmentsHandler
}

func (o *DeleteBackupRuntimeEnvironments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteBackupRuntimeEnvironmentsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
