// Code generated by go-swagger; DO NOT EDIT.

package backup_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// DownloadBackupRuntimeEnvironmentsOKCode is the HTTP code returned for type DownloadBackupRuntimeEnvironmentsOK
const DownloadBackupRuntimeEnvironmentsOKCode int = 200

/*DownloadBackupRuntimeEnvironmentsOK Backup downloaded with success

swagger:response downloadBackupRuntimeEnvironmentsOK
*/
type DownloadBackupRuntimeEnvironmentsOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewDownloadBackupRuntimeEnvironmentsOK creates DownloadBackupRuntimeEnvironmentsOK with default headers values
func NewDownloadBackupRuntimeEnvironmentsOK() *DownloadBackupRuntimeEnvironmentsOK {

	return &DownloadBackupRuntimeEnvironmentsOK{}
}

// WithPayload adds the payload to the download backup runtime environments o k response
func (o *DownloadBackupRuntimeEnvironmentsOK) WithPayload(payload io.ReadCloser) *DownloadBackupRuntimeEnvironmentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download backup runtime environments o k response
func (o *DownloadBackupRuntimeEnvironmentsOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadBackupRuntimeEnvironmentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DownloadBackupRuntimeEnvironmentsBadRequestCode is the HTTP code returned for type DownloadBackupRuntimeEnvironmentsBadRequest
const DownloadBackupRuntimeEnvironmentsBadRequestCode int = 400

/*DownloadBackupRuntimeEnvironmentsBadRequest Bad request

swagger:response downloadBackupRuntimeEnvironmentsBadRequest
*/
type DownloadBackupRuntimeEnvironmentsBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDownloadBackupRuntimeEnvironmentsBadRequest creates DownloadBackupRuntimeEnvironmentsBadRequest with default headers values
func NewDownloadBackupRuntimeEnvironmentsBadRequest() *DownloadBackupRuntimeEnvironmentsBadRequest {

	return &DownloadBackupRuntimeEnvironmentsBadRequest{}
}

// WithPayload adds the payload to the download backup runtime environments bad request response
func (o *DownloadBackupRuntimeEnvironmentsBadRequest) WithPayload(payload string) *DownloadBackupRuntimeEnvironmentsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download backup runtime environments bad request response
func (o *DownloadBackupRuntimeEnvironmentsBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadBackupRuntimeEnvironmentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DownloadBackupRuntimeEnvironmentsInternalServerErrorCode is the HTTP code returned for type DownloadBackupRuntimeEnvironmentsInternalServerError
const DownloadBackupRuntimeEnvironmentsInternalServerErrorCode int = 500

/*DownloadBackupRuntimeEnvironmentsInternalServerError Internal error

swagger:response downloadBackupRuntimeEnvironmentsInternalServerError
*/
type DownloadBackupRuntimeEnvironmentsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDownloadBackupRuntimeEnvironmentsInternalServerError creates DownloadBackupRuntimeEnvironmentsInternalServerError with default headers values
func NewDownloadBackupRuntimeEnvironmentsInternalServerError() *DownloadBackupRuntimeEnvironmentsInternalServerError {

	return &DownloadBackupRuntimeEnvironmentsInternalServerError{}
}

// WithPayload adds the payload to the download backup runtime environments internal server error response
func (o *DownloadBackupRuntimeEnvironmentsInternalServerError) WithPayload(payload string) *DownloadBackupRuntimeEnvironmentsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download backup runtime environments internal server error response
func (o *DownloadBackupRuntimeEnvironmentsInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadBackupRuntimeEnvironmentsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
