// Code generated by go-swagger; DO NOT EDIT.

package backup_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewImportBackupRuntimeEnvironmentsParams creates a new ImportBackupRuntimeEnvironmentsParams object
// no default values defined in spec.
func NewImportBackupRuntimeEnvironmentsParams() ImportBackupRuntimeEnvironmentsParams {

	return ImportBackupRuntimeEnvironmentsParams{}
}

// ImportBackupRuntimeEnvironmentsParams contains all the bound params for the import backup runtime environments operation
// typically these are obtained from a http.Request
//
// swagger:parameters importBackupRuntimeEnvironments
type ImportBackupRuntimeEnvironmentsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Backup archive to upload
	  In: formData
	*/
	File io.ReadCloser
	/*Backup archive to download from microservice
	  In: formData
	*/
	URL *string
	/*RuntimeEnvironment providerId
	  Required: true
	  In: path
	*/
	ProviderID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewImportBackupRuntimeEnvironmentsParams() beforehand.
func (o *ImportBackupRuntimeEnvironmentsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}
	fds := runtime.Values(r.Form)

	file, fileHeader, err := r.FormFile("File")
	if err != nil && err != http.ErrMissingFile {
		res = append(res, errors.New(400, "reading file %q failed: %v", "file", err))
	} else if err == http.ErrMissingFile {
		// no-op for missing but optional file parameter
	} else if err := o.bindFile(file, fileHeader); err != nil {
		res = append(res, err)
	} else {
		o.File = &runtime.File{Data: file, Header: fileHeader}
	}

	fdURL, fdhkURL, _ := fds.GetOK("Url")
	if err := o.bindURL(fdURL, fdhkURL, route.Formats); err != nil {
		res = append(res, err)
	}

	rProviderID, rhkProviderID, _ := route.Params.GetOK("providerId")
	if err := o.bindProviderID(rProviderID, rhkProviderID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFile binds file parameter File.
//
// The only supported validations on files are MinLength and MaxLength
func (o *ImportBackupRuntimeEnvironmentsParams) bindFile(file multipart.File, header *multipart.FileHeader) error {
	return nil
}

// bindURL binds and validates parameter URL from formData.
func (o *ImportBackupRuntimeEnvironmentsParams) bindURL(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.URL = &raw

	return nil
}

// bindProviderID binds and validates parameter ProviderID from path.
func (o *ImportBackupRuntimeEnvironmentsParams) bindProviderID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ProviderID = raw

	return nil
}
