// Code generated by go-swagger; DO NOT EDIT.

package backup_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gitlab.com/kathra/kathra/kathra-services/kathra-runtimemanager/kathra-runtimemanager-go/kathra-runtimemanager-k8s/models"
)

// ImportBackupRuntimeEnvironmentsOKCode is the HTTP code returned for type ImportBackupRuntimeEnvironmentsOK
const ImportBackupRuntimeEnvironmentsOKCode int = 200

/*ImportBackupRuntimeEnvironmentsOK RuntimeAppInstance deployed with success

swagger:response importBackupRuntimeEnvironmentsOK
*/
type ImportBackupRuntimeEnvironmentsOK struct {

	/*
	  In: Body
	*/
	Payload *models.RuntimeEnvironmentBackup `json:"body,omitempty"`
}

// NewImportBackupRuntimeEnvironmentsOK creates ImportBackupRuntimeEnvironmentsOK with default headers values
func NewImportBackupRuntimeEnvironmentsOK() *ImportBackupRuntimeEnvironmentsOK {

	return &ImportBackupRuntimeEnvironmentsOK{}
}

// WithPayload adds the payload to the import backup runtime environments o k response
func (o *ImportBackupRuntimeEnvironmentsOK) WithPayload(payload *models.RuntimeEnvironmentBackup) *ImportBackupRuntimeEnvironmentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the import backup runtime environments o k response
func (o *ImportBackupRuntimeEnvironmentsOK) SetPayload(payload *models.RuntimeEnvironmentBackup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ImportBackupRuntimeEnvironmentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ImportBackupRuntimeEnvironmentsBadRequestCode is the HTTP code returned for type ImportBackupRuntimeEnvironmentsBadRequest
const ImportBackupRuntimeEnvironmentsBadRequestCode int = 400

/*ImportBackupRuntimeEnvironmentsBadRequest Bad request

swagger:response importBackupRuntimeEnvironmentsBadRequest
*/
type ImportBackupRuntimeEnvironmentsBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewImportBackupRuntimeEnvironmentsBadRequest creates ImportBackupRuntimeEnvironmentsBadRequest with default headers values
func NewImportBackupRuntimeEnvironmentsBadRequest() *ImportBackupRuntimeEnvironmentsBadRequest {

	return &ImportBackupRuntimeEnvironmentsBadRequest{}
}

// WithPayload adds the payload to the import backup runtime environments bad request response
func (o *ImportBackupRuntimeEnvironmentsBadRequest) WithPayload(payload string) *ImportBackupRuntimeEnvironmentsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the import backup runtime environments bad request response
func (o *ImportBackupRuntimeEnvironmentsBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ImportBackupRuntimeEnvironmentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ImportBackupRuntimeEnvironmentsInternalServerErrorCode is the HTTP code returned for type ImportBackupRuntimeEnvironmentsInternalServerError
const ImportBackupRuntimeEnvironmentsInternalServerErrorCode int = 500

/*ImportBackupRuntimeEnvironmentsInternalServerError Internal error

swagger:response importBackupRuntimeEnvironmentsInternalServerError
*/
type ImportBackupRuntimeEnvironmentsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewImportBackupRuntimeEnvironmentsInternalServerError creates ImportBackupRuntimeEnvironmentsInternalServerError with default headers values
func NewImportBackupRuntimeEnvironmentsInternalServerError() *ImportBackupRuntimeEnvironmentsInternalServerError {

	return &ImportBackupRuntimeEnvironmentsInternalServerError{}
}

// WithPayload adds the payload to the import backup runtime environments internal server error response
func (o *ImportBackupRuntimeEnvironmentsInternalServerError) WithPayload(payload string) *ImportBackupRuntimeEnvironmentsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the import backup runtime environments internal server error response
func (o *ImportBackupRuntimeEnvironmentsInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ImportBackupRuntimeEnvironmentsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
