// Code generated by go-swagger; DO NOT EDIT.

package backup_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RestoreBackupRuntimeEnvironmentsHandlerFunc turns a function with the right signature into a restore backup runtime environments handler
type RestoreBackupRuntimeEnvironmentsHandlerFunc func(RestoreBackupRuntimeEnvironmentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RestoreBackupRuntimeEnvironmentsHandlerFunc) Handle(params RestoreBackupRuntimeEnvironmentsParams) middleware.Responder {
	return fn(params)
}

// RestoreBackupRuntimeEnvironmentsHandler interface for that can handle valid restore backup runtime environments params
type RestoreBackupRuntimeEnvironmentsHandler interface {
	Handle(RestoreBackupRuntimeEnvironmentsParams) middleware.Responder
}

// NewRestoreBackupRuntimeEnvironments creates a new http.Handler for the restore backup runtime environments operation
func NewRestoreBackupRuntimeEnvironments(ctx *middleware.Context, handler RestoreBackupRuntimeEnvironmentsHandler) *RestoreBackupRuntimeEnvironments {
	return &RestoreBackupRuntimeEnvironments{Context: ctx, Handler: handler}
}

/*RestoreBackupRuntimeEnvironments swagger:route POST /runtimeEnvironments/{providerId}/backups/{providerIdBackup}/restore Backup management restoreBackupRuntimeEnvironments

Restore backup into RuntimeEnvironment

*/
type RestoreBackupRuntimeEnvironments struct {
	Context *middleware.Context
	Handler RestoreBackupRuntimeEnvironmentsHandler
}

func (o *RestoreBackupRuntimeEnvironments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRestoreBackupRuntimeEnvironmentsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
