// Code generated by go-swagger; DO NOT EDIT.

package container_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteRuntimeContainerOKCode is the HTTP code returned for type DeleteRuntimeContainerOK
const DeleteRuntimeContainerOKCode int = 200

/*DeleteRuntimeContainerOK RuntimeContainer killed

swagger:response deleteRuntimeContainerOK
*/
type DeleteRuntimeContainerOK struct {
}

// NewDeleteRuntimeContainerOK creates DeleteRuntimeContainerOK with default headers values
func NewDeleteRuntimeContainerOK() *DeleteRuntimeContainerOK {

	return &DeleteRuntimeContainerOK{}
}

// WriteResponse to the client
func (o *DeleteRuntimeContainerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteRuntimeContainerBadRequestCode is the HTTP code returned for type DeleteRuntimeContainerBadRequest
const DeleteRuntimeContainerBadRequestCode int = 400

/*DeleteRuntimeContainerBadRequest Bad request

swagger:response deleteRuntimeContainerBadRequest
*/
type DeleteRuntimeContainerBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteRuntimeContainerBadRequest creates DeleteRuntimeContainerBadRequest with default headers values
func NewDeleteRuntimeContainerBadRequest() *DeleteRuntimeContainerBadRequest {

	return &DeleteRuntimeContainerBadRequest{}
}

// WithPayload adds the payload to the delete runtime container bad request response
func (o *DeleteRuntimeContainerBadRequest) WithPayload(payload string) *DeleteRuntimeContainerBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete runtime container bad request response
func (o *DeleteRuntimeContainerBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRuntimeContainerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteRuntimeContainerNotFoundCode is the HTTP code returned for type DeleteRuntimeContainerNotFound
const DeleteRuntimeContainerNotFoundCode int = 404

/*DeleteRuntimeContainerNotFound Not found

swagger:response deleteRuntimeContainerNotFound
*/
type DeleteRuntimeContainerNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteRuntimeContainerNotFound creates DeleteRuntimeContainerNotFound with default headers values
func NewDeleteRuntimeContainerNotFound() *DeleteRuntimeContainerNotFound {

	return &DeleteRuntimeContainerNotFound{}
}

// WithPayload adds the payload to the delete runtime container not found response
func (o *DeleteRuntimeContainerNotFound) WithPayload(payload string) *DeleteRuntimeContainerNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete runtime container not found response
func (o *DeleteRuntimeContainerNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRuntimeContainerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteRuntimeContainerInternalServerErrorCode is the HTTP code returned for type DeleteRuntimeContainerInternalServerError
const DeleteRuntimeContainerInternalServerErrorCode int = 500

/*DeleteRuntimeContainerInternalServerError Internal error

swagger:response deleteRuntimeContainerInternalServerError
*/
type DeleteRuntimeContainerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteRuntimeContainerInternalServerError creates DeleteRuntimeContainerInternalServerError with default headers values
func NewDeleteRuntimeContainerInternalServerError() *DeleteRuntimeContainerInternalServerError {

	return &DeleteRuntimeContainerInternalServerError{}
}

// WithPayload adds the payload to the delete runtime container internal server error response
func (o *DeleteRuntimeContainerInternalServerError) WithPayload(payload string) *DeleteRuntimeContainerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete runtime container internal server error response
func (o *DeleteRuntimeContainerInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRuntimeContainerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
