// Code generated by go-swagger; DO NOT EDIT.

package container_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// GetRuntimeContainerURL generates an URL for the get runtime container operation
type GetRuntimeContainerURL struct {
	ProviderIDAI string
	ProviderIDRE string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetRuntimeContainerURL) WithBasePath(bp string) *GetRuntimeContainerURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetRuntimeContainerURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetRuntimeContainerURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/runtimeEnvironments/{providerIdRE}/applications/{providerIdAI}/containers"

	providerIDAI := o.ProviderIDAI
	if providerIDAI != "" {
		_path = strings.Replace(_path, "{providerIdAI}", providerIDAI, -1)
	} else {
		return nil, errors.New("providerIdAI is required on GetRuntimeContainerURL")
	}

	providerIDRE := o.ProviderIDRE
	if providerIDRE != "" {
		_path = strings.Replace(_path, "{providerIdRE}", providerIDRE, -1)
	} else {
		return nil, errors.New("providerIdRE is required on GetRuntimeContainerURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetRuntimeContainerURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetRuntimeContainerURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetRuntimeContainerURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetRuntimeContainerURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetRuntimeContainerURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetRuntimeContainerURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
