// Code generated by go-swagger; DO NOT EDIT.

package container_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRuntimeContainerHandlerFunc turns a function with the right signature into a get runtime container handler
type GetRuntimeContainerHandlerFunc func(GetRuntimeContainerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRuntimeContainerHandlerFunc) Handle(params GetRuntimeContainerParams) middleware.Responder {
	return fn(params)
}

// GetRuntimeContainerHandler interface for that can handle valid get runtime container params
type GetRuntimeContainerHandler interface {
	Handle(GetRuntimeContainerParams) middleware.Responder
}

// NewGetRuntimeContainer creates a new http.Handler for the get runtime container operation
func NewGetRuntimeContainer(ctx *middleware.Context, handler GetRuntimeContainerHandler) *GetRuntimeContainer {
	return &GetRuntimeContainer{Context: ctx, Handler: handler}
}

/*GetRuntimeContainer swagger:route GET /runtimeEnvironments/{providerIdRE}/applications/{providerIdAI}/containers Container management getRuntimeContainer

Get RuntimeContainer

*/
type GetRuntimeContainer struct {
	Context *middleware.Context
	Handler GetRuntimeContainerHandler
}

func (o *GetRuntimeContainer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRuntimeContainerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
