// Code generated by go-swagger; DO NOT EDIT.

package application_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteApplicationOKCode is the HTTP code returned for type DeleteApplicationOK
const DeleteApplicationOKCode int = 200

/*DeleteApplicationOK RuntimeAppInstance deleted

swagger:response deleteApplicationOK
*/
type DeleteApplicationOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteApplicationOK creates DeleteApplicationOK with default headers values
func NewDeleteApplicationOK() *DeleteApplicationOK {

	return &DeleteApplicationOK{}
}

// WithPayload adds the payload to the delete application o k response
func (o *DeleteApplicationOK) WithPayload(payload string) *DeleteApplicationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete application o k response
func (o *DeleteApplicationOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteApplicationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteApplicationBadRequestCode is the HTTP code returned for type DeleteApplicationBadRequest
const DeleteApplicationBadRequestCode int = 400

/*DeleteApplicationBadRequest Bad request

swagger:response deleteApplicationBadRequest
*/
type DeleteApplicationBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteApplicationBadRequest creates DeleteApplicationBadRequest with default headers values
func NewDeleteApplicationBadRequest() *DeleteApplicationBadRequest {

	return &DeleteApplicationBadRequest{}
}

// WithPayload adds the payload to the delete application bad request response
func (o *DeleteApplicationBadRequest) WithPayload(payload string) *DeleteApplicationBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete application bad request response
func (o *DeleteApplicationBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteApplicationBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteApplicationNotFoundCode is the HTTP code returned for type DeleteApplicationNotFound
const DeleteApplicationNotFoundCode int = 404

/*DeleteApplicationNotFound Not found

swagger:response deleteApplicationNotFound
*/
type DeleteApplicationNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteApplicationNotFound creates DeleteApplicationNotFound with default headers values
func NewDeleteApplicationNotFound() *DeleteApplicationNotFound {

	return &DeleteApplicationNotFound{}
}

// WithPayload adds the payload to the delete application not found response
func (o *DeleteApplicationNotFound) WithPayload(payload string) *DeleteApplicationNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete application not found response
func (o *DeleteApplicationNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteApplicationNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteApplicationInternalServerErrorCode is the HTTP code returned for type DeleteApplicationInternalServerError
const DeleteApplicationInternalServerErrorCode int = 500

/*DeleteApplicationInternalServerError Internal error

swagger:response deleteApplicationInternalServerError
*/
type DeleteApplicationInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteApplicationInternalServerError creates DeleteApplicationInternalServerError with default headers values
func NewDeleteApplicationInternalServerError() *DeleteApplicationInternalServerError {

	return &DeleteApplicationInternalServerError{}
}

// WithPayload adds the payload to the delete application internal server error response
func (o *DeleteApplicationInternalServerError) WithPayload(payload string) *DeleteApplicationInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete application internal server error response
func (o *DeleteApplicationInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteApplicationInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
