// Code generated by go-swagger; DO NOT EDIT.

package application_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteApplicationHandlerFunc turns a function with the right signature into a delete application handler
type DeleteApplicationHandlerFunc func(DeleteApplicationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteApplicationHandlerFunc) Handle(params DeleteApplicationParams) middleware.Responder {
	return fn(params)
}

// DeleteApplicationHandler interface for that can handle valid delete application params
type DeleteApplicationHandler interface {
	Handle(DeleteApplicationParams) middleware.Responder
}

// NewDeleteApplication creates a new http.Handler for the delete application operation
func NewDeleteApplication(ctx *middleware.Context, handler DeleteApplicationHandler) *DeleteApplication {
	return &DeleteApplication{Context: ctx, Handler: handler}
}

/*DeleteApplication swagger:route DELETE /runtimeEnvironments/{providerIdRE}/applications/{providerIdAI} Application management deleteApplication

Delete application

*/
type DeleteApplication struct {
	Context *middleware.Context
	Handler DeleteApplicationHandler
}

func (o *DeleteApplication) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteApplicationParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
