// Code generated by go-swagger; DO NOT EDIT.

package application_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gitlab.com/kathra/kathra/kathra-services/kathra-runtimemanager/kathra-runtimemanager-go/kathra-runtimemanager-k8s/models"
)

// GetRuntimeAppServicesOKCode is the HTTP code returned for type GetRuntimeAppServicesOK
const GetRuntimeAppServicesOKCode int = 200

/*GetRuntimeAppServicesOK RuntimeAppService from RuntimeAppInstance

swagger:response getRuntimeAppServicesOK
*/
type GetRuntimeAppServicesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.RuntimeAppService `json:"body,omitempty"`
}

// NewGetRuntimeAppServicesOK creates GetRuntimeAppServicesOK with default headers values
func NewGetRuntimeAppServicesOK() *GetRuntimeAppServicesOK {

	return &GetRuntimeAppServicesOK{}
}

// WithPayload adds the payload to the get runtime app services o k response
func (o *GetRuntimeAppServicesOK) WithPayload(payload []*models.RuntimeAppService) *GetRuntimeAppServicesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get runtime app services o k response
func (o *GetRuntimeAppServicesOK) SetPayload(payload []*models.RuntimeAppService) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRuntimeAppServicesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.RuntimeAppService, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRuntimeAppServicesBadRequestCode is the HTTP code returned for type GetRuntimeAppServicesBadRequest
const GetRuntimeAppServicesBadRequestCode int = 400

/*GetRuntimeAppServicesBadRequest Bad request

swagger:response getRuntimeAppServicesBadRequest
*/
type GetRuntimeAppServicesBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetRuntimeAppServicesBadRequest creates GetRuntimeAppServicesBadRequest with default headers values
func NewGetRuntimeAppServicesBadRequest() *GetRuntimeAppServicesBadRequest {

	return &GetRuntimeAppServicesBadRequest{}
}

// WithPayload adds the payload to the get runtime app services bad request response
func (o *GetRuntimeAppServicesBadRequest) WithPayload(payload string) *GetRuntimeAppServicesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get runtime app services bad request response
func (o *GetRuntimeAppServicesBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRuntimeAppServicesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRuntimeAppServicesNotFoundCode is the HTTP code returned for type GetRuntimeAppServicesNotFound
const GetRuntimeAppServicesNotFoundCode int = 404

/*GetRuntimeAppServicesNotFound Not found

swagger:response getRuntimeAppServicesNotFound
*/
type GetRuntimeAppServicesNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetRuntimeAppServicesNotFound creates GetRuntimeAppServicesNotFound with default headers values
func NewGetRuntimeAppServicesNotFound() *GetRuntimeAppServicesNotFound {

	return &GetRuntimeAppServicesNotFound{}
}

// WithPayload adds the payload to the get runtime app services not found response
func (o *GetRuntimeAppServicesNotFound) WithPayload(payload string) *GetRuntimeAppServicesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get runtime app services not found response
func (o *GetRuntimeAppServicesNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRuntimeAppServicesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRuntimeAppServicesInternalServerErrorCode is the HTTP code returned for type GetRuntimeAppServicesInternalServerError
const GetRuntimeAppServicesInternalServerErrorCode int = 500

/*GetRuntimeAppServicesInternalServerError Internal error

swagger:response getRuntimeAppServicesInternalServerError
*/
type GetRuntimeAppServicesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetRuntimeAppServicesInternalServerError creates GetRuntimeAppServicesInternalServerError with default headers values
func NewGetRuntimeAppServicesInternalServerError() *GetRuntimeAppServicesInternalServerError {

	return &GetRuntimeAppServicesInternalServerError{}
}

// WithPayload adds the payload to the get runtime app services internal server error response
func (o *GetRuntimeAppServicesInternalServerError) WithPayload(payload string) *GetRuntimeAppServicesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get runtime app services internal server error response
func (o *GetRuntimeAppServicesInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRuntimeAppServicesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
