// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CatalogEntryArgument catalog entry argument
// swagger:model CatalogEntryArgument
type CatalogEntryArgument struct {

	// Argument constraint for catalog entry
	Contrainst string `json:"contrainst,omitempty"`

	// Description argument for catalog entry
	Description string `json:"description,omitempty"`

	// Argument key for catalog entry
	Key string `json:"key,omitempty"`

	// Readable argument for catalog entry
	Label string `json:"label,omitempty"`

	// Argument value for catalog entry
	Value string `json:"value,omitempty"`
}

// Validate validates this catalog entry argument
func (m *CatalogEntryArgument) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CatalogEntryArgument) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CatalogEntryArgument) UnmarshalBinary(b []byte) error {
	var res CatalogEntryArgument
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
