// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RuntimeHTTPLoadBalancer runtime Http load balancer
// swagger:model RuntimeHttpLoadBalancer
type RuntimeHTTPLoadBalancer struct {

	// Rules
	ForwardingRules []*RuntimeHTTPLoadBalancerForwarding `json:"forwardingRules"`

	// Hostname
	Hostname string `json:"hostname,omitempty"`

	// RuntimeLoadBalancer name
	Name string `json:"name,omitempty"`

	// Incoming port number
	Port int64 `json:"port,omitempty"`

	// RuntimeLoadBalancer providerId
	ProviderID string `json:"providerId,omitempty"`

	// Rewrite target path
	RewriteURL string `json:"rewriteUrl,omitempty"`
}

// Validate validates this runtime Http load balancer
func (m *RuntimeHTTPLoadBalancer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateForwardingRules(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RuntimeHTTPLoadBalancer) validateForwardingRules(formats strfmt.Registry) error {

	if swag.IsZero(m.ForwardingRules) { // not required
		return nil
	}

	for i := 0; i < len(m.ForwardingRules); i++ {
		if swag.IsZero(m.ForwardingRules[i]) { // not required
			continue
		}

		if m.ForwardingRules[i] != nil {
			if err := m.ForwardingRules[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("forwardingRules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RuntimeHTTPLoadBalancer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RuntimeHTTPLoadBalancer) UnmarshalBinary(b []byte) error {
	var res RuntimeHTTPLoadBalancer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
