// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RuntimeAppServicePort runtime app service port
// swagger:model RuntimeAppServicePort
type RuntimeAppServicePort struct {

	// Port number
	Port int64 `json:"port,omitempty"`

	// Protocol
	Protocol string `json:"protocol,omitempty"`

	// Port number to redirect
	TargetPort string `json:"targetPort,omitempty"`
}

// Validate validates this runtime app service port
func (m *RuntimeAppServicePort) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RuntimeAppServicePort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RuntimeAppServicePort) UnmarshalBinary(b []byte) error {
	var res RuntimeAppServicePort
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
