// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RuntimeHTTPLoadBalancerForwarding runtime Http load balancer forwarding
// swagger:model RuntimeHttpLoadBalancerForwarding
type RuntimeHTTPLoadBalancerForwarding struct {

	// Port outcoming
	Port string `json:"port,omitempty"`

	// Path rule incoming
	Rule string `json:"rule,omitempty"`

	// Service outcoming
	Service string `json:"service,omitempty"`
}

// Validate validates this runtime Http load balancer forwarding
func (m *RuntimeHTTPLoadBalancerForwarding) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RuntimeHTTPLoadBalancerForwarding) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RuntimeHTTPLoadBalancerForwarding) UnmarshalBinary(b []byte) error {
	var res RuntimeHTTPLoadBalancerForwarding
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
